name: hotel_lemon_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dots_indicator: ^3.0.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  badges: ^3.1.1
  animated_text_kit: ^4.2.2
  lottie: ^2.6.0
  image: ^3.3.0
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.4.0
  geocoding: ^2.1.0
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application,
  assets:
    - assets/
    - assets/icons/
    - assets/animation/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
