class Product {
  final String name;
  final String category;
  final double price;
  final String? imaUrl;
  final bool isRecommended;
  final bool isPopular;
  final bool isRecentlyadded;
  final bool isDrink;

  const Product({
    required this.name,
    required this.category,
    required this.price,
    this.imaUrl,
    required this.isRecommended,
    required this.isPopular,
    required this.isRecentlyadded,
    required this.isDrink,
  });

  static List<Product> products = [
    Product(
      name: "Hot Lemon",
      category: "Tea & Coffee",
      price: 40,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Lemon Tea",
      category: "Tea & Coffee",
      price: 30,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Coffee",
      category: " Tea & Coffee",
      price: 70,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Milk Tea",
      category: "Tea & Coffee",
      price: 40,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Milk Coffee",
      category: "Tea & Coffee",
      price: 70,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Milk with Honey",
      category: " Tea & Coffee",
      price: 100,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Hot Milk ",
      category: "Tea & Coffee",
      price: 80,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Cold Coffee",
      category: "Tea & Coffee",
      price: 100,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Chocolate Milk Shake",
      category: "Lassi",
      price: 130,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: " Hot Lemon with honey",
      category: " Tea & Coffee",
      price: 100,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Milk Shake",
      category: "Lassi",
      price: 100,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Butter Jam Toast",
      category: "BreakFast",
      price: 100,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Fried Egg",
      category: "BreakFast",
      price: 75,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Honey Toast",
      category: " BreakFast",
      price: 80,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Boiled Egg ",
      category: "BreakFast",
      price: 60,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Plain Omlet",
      category: "BreakFast",
      price: 60,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Masala Omlet  ",
      category: "BreakFast",
      price: 3.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Egg Pouch",
      category: " BreakFast",
      price: 110,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Egg Bhujia",
      category: "BreakFast",
      price: 120,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),

    Product(
      name: "Nepali Salad ",
      category: "Salad",
      price: 100,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Salad",
      category: "Salad",
      price: 120,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fruit Salad",
      category: "Salad",
      price: 150,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Macroni Salad",
      category: "Salad",
      price: 170,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chocolate Lassi ",
      category: "Lassi",
      price: 130,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Plane Lassi",
      category: "Lassi",
      price: 80,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Cold Lassi",
      category: "Lassi",
      price: 100,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Banana Lassi",
      category: "Lassi",
      price: 130,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vanilla Lassi ",
      category: "Lassi",
      price: 140,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Sweet Lassi",
      category: "Salad",
      price: 120,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Veg.Sandwich",
      category: "Sandwich",
      price: 120,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Sandwich",
      category: "Sandwich",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Club Sandwich",
      category: "Sandwich",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Egg Sandwich",
      category: "Sandwich",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: " Lemon Chicken",
      category: "Special Dish",
      price: 320,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Chicken Satay",
      category: "Special Dish",
      price: 320,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Chicken Shashlik ",
      category: "Special Dish",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Veg.Steam Momo",
      category: "Mo:Mo",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Chicken Steam Momo",
      category: "Mo:Mo",
      price: 125,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
    ),
    Product(
      name: "Mutton Steam Momo ",
      category: "Mo:Mo",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Jhol Momo",
      category: "Mo:Mo",
      price: 130,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Jhol Momo",
      category: "Mo:Mo",
      price: 160,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Jhol Momo",
      category: "Mo:Mo",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Fry Momo",
      category: "Mo:Mo",
      price: 140,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Fry Momo ",
      category: "Mo:Mo",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Kothay Momo ",
      category: "Mo:Mo",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Kothay Momo",
      category: "Mo:Mo",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Momo Sadheko ",
      category: "Mo:Mo",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Momo Sadheko",
      category: "Mo:Mo",
      price: 220,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Momo Chilli ",
      category: "Chilli Items",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Momo Chilli ",
      category: "Chilli Items",
      price: 140,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Chilli",
      category: "Chilli Items",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Sauces Chilli ",
      category: "Chilli Items",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Paneer Chilli ",
      category: "Chilli Items",
      price: 320,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mushroom Chilli ",
      category: "Chilli Items",
      price: 220,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mushroom Babycorn Chilli ",
      category: "Chilli Items",
      price: 220,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chips Chilli ",
      category: "Chilli Items",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Chowmin",
      category: "Chowmin",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Chowmin",
      category: "Chowmin",
      price: 125,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Chowmin",
      category: "Chowmin",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Egg Chowmin ",
      category: "Chowmin",
      price: 125,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mushroom Chowmin",
      category: "Chowmin",
      price: 130,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Paneer Chowmin",
      category: "Chowmin",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Thupa",
      category: "Thukpa",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Thupa",
      category: "Thukpa",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mix Thupa ",
      category: "Thukpa",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Wrap & Roll",
      category: "Wraps & Rolls",
      price: 160,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Spring Roll",
      category: "Wraps & Rolls",
      price: 160,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Spring Roll",
      category: "Wraps & Rolls",
      price: 220,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Egg Spring Roll",
      category: "Wraps & Rolls",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Spring Roll",
      category: "Wraps & Rolls",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Plain Jeera Fried Rice",
      category: "Fried Rice",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Veg. Fried Rice",
      category: "Fried Rice",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Fried Rice",
      category: "Fried Rice",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Fried Rice",
      category: "Fried Rice",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mushroom Fried Rice",
      category: "Fried Rice",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Paneer Fried Rice",
      category: "Fried Rice",
      price: 220,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mix Fried Rice",
      category: "Fried Rice",
      price: 270,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Egg Fried Rice",
      category: "Fried Rice",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chicken Pizza",
      category: "Pizza",
      price: 425,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mushroom Pizza ",
      category: "Pizza",
      price: 375,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Paneer Pizza",
      category: "Pizza",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Hawaii Pizza",
      category: "Pizza",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mutton Pizza",
      category: "Pizza",
      price: 500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Cheese Pizza",
      category: "Pizza",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chatpate",
      category: "Vegeterian Snacks",
      price: 75,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Special Chatpate",
      category: "Vegeterian Snacks",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Chauchau Sadheko",
      category: "Vegeterian Snacks",
      price: 125,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Alu Jeera",
      category: "Vegeterian Snacks",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Alu Sadeko",
      category: "Vegeterian Snacks",
      price: 125,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    // Product(
    //   name: "Alu Chilli",
    //   category: "Vegeterian Snacks",
    //   price: 2.50,
    //   isPopular: false,
    //   isRecommended: false,
    //   isRecentlyadded: false,
    //   isDrink: true,
    // ),
    Product(
      name: "Veg. Pakauda",
      category: "Vegeterian Snacks",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Cheese Ball",
      category: "Vegeterian Snacks",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Paneer Pakauda",
      category: "Vegeterian Snacks",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Mushroom Pakauda",
      category: "Vegeterian Snacks",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
    ),
    Product(
      name: "Onion Pakauda",
      category: "Vegeterian Snacks",
      price: 150,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Peanut Sadeko",
      category: "Vegeterian Snacks",
      price: 150,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vatmas Sadeko",
      category: "Vegeterian Snacks",
      price: 125,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vatmas Chiura",
      category: "Vegeterian Snacks",
      price: 125,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "French Fry",
      category: "Vegeterian Snacks",
      price: 120,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chiura Bhujiya",
      category: "Vegeterian Snacks",
      price: 80,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Dry Papad",
      category: "Vegeterian Snacks",
      price: 60,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fry Papad",
      category: "Vegeterian Snacks",
      price: 80,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Kaju Fry",
      category: "Vegeterian Snacks",
      price: 250,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Plain Kaju",
      category: "Vegeterian Snacks",
      price: 220,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mushroom Fry",
      category: "Vegeterian Snacks",
      price: 180,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
    ),

    Product(
      name: "Chicken Popcorn",
      category: "Non-Veg Snacks",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Chatpate ",
      category: "Non-Veg Snacks",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Roast",
      category: "Non-Veg Snacks",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken(Filla+Wings)",
      category: "Non-Veg Snacks",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Lolipop Roast",
      category: "Non-Veg Snacks",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Lolipop Crunchy",
      category: "Non-Veg Snacks",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Drumsticks",
      category: "Non-Veg Snacks",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Pakauda",
      category: "Non-Veg Snacks",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Fry",
      category: "Non-Veg Snacks",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Kurkure",
      category: "Non-Veg Snacks",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Meat Ball",
      category: "Non-Veg Snacks",
      price: 280,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Sauces Fry",
      category: "Non-Veg Snacks",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Chhoila",
      category: "Non-Veg Snacks",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Sadeko",
      category: "Non-Veg Snacks",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken 65",
      category: "Non-Veg Snacks",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Garlic Chicken",
      category: "Non-Veg Snacks ",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Lamp",
      category: "Non-Veg Snacks",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Boiled",
      category: "Non-Veg Snacks",
      price: 220,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Roast (Full)",
      category: "Non-Veg Snacks",
      price: 1000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),

    Product(
      name: "Mutton Chilli",
      category: "Mutton Non-Veg Special",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Boiled with Nepali Achar",
      category: "Mutton Non-Veg Special",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Meat Ball",
      category: "Mutton Non-Veg Special",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton boil poleko",
      category: "Mutton Non-Veg Special",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Bhutan",
      category: "Mutton Non-Veg Special",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Head Boil",
      category: "Mutton Non-Veg Special",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Roast (Full)",
      category: "Mutton Non-Veg Special",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Sadeko",
      category: "Mutton Non-Veg Special",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Tandoori (Full)",
      category: "Tandori Special",
      price: 1000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Tandoori (Half)",
      category: "Tandori Special",
      price: 550,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Tika",
      category: "Tandori Special",
      price: 280,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Tangri Kabab",
      category: "Tandori Special",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Paneer Tika",
      category: "Tandori Special",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Butter Nan Per Pcs",
      category: "Tandori Special",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Plain Nan Per Pcs",
      category: "Tandori Special",
      price: 60,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Tandoori Roti",
      category: "Tandori Special",
      price: 30,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Alu Paratha Per Pcs",
      category: "Tandori Special",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Plain Paratha Kulcha Per Pcs",
      category: "Tandori Special",
      price: 50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Kulcha Per Pcs",
      category: "Tandori Special",
      price: 40,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Butter Kulcha Per Pcs",
      category: "Tandori Special",
      price: 50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Local Chicken Sekuwa",
      category: "Sekuwa & Poleko",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Sekuwa",
      category: "Sekuwa & Poleko",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Sekuwa",
      category: "Sekuwa & Poleko",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Poleko",
      category: "Sekuwa & Poleko",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Poleko",
      category: "Sekuwa & Poleko",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Chili",
      category: "Fish Items",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Fry",
      category: "Fish Items",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Finger",
      category: "Fish Items",
      price: 230,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Ball",
      category: "Fish Items",
      price: 210,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Curry",
      category: "Fish Items",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Veg. Thakali Set/Roti ",
      category: "Thakali set",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Thakali Set/Roti",
      category: "Thakali set",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "L.Chicken Thakali Set/Roti",
      category: "Thakali set",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Thakali Set/Roti",
      category: "Thakali set",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Thakali Set/Roti",
      category: "Thakali set",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Special Mutton Set/Roti",
      category: "Thakali set",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Paneer Butter Masala",
      category: "Veg-Curry",
      price: 280,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Matar Paneer",
      category: "Veg-Curry",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Alu Matar",
      category: "Veg-Curry",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mix Veg. Curry",
      category: "Veg-Curry",
      price: 210,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Alu Gobi",
      category: "Veg-Curry",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),

    Product(
      name: "Veg. Manchurian",
      category: "Veg-Curry",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Alu Dum",
      category: "Veg-Curry",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Plain Daal",
      category: "Veg-Curry",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Daal Fried",
      category: "Veg-Curry",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Daal Tadaka",
      category: "Veg-Curry",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Curry",
      category: "Non-Veg Curry",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Curry",
      category: "Non-Veg Curry",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Egg Curry",
      category: "Non-Veg Curry",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Kima Curry",
      category: "Non-Veg Curry",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Butter Masala",
      category: "Non-Veg Curry",
      price: 280,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Tika Masala",
      category: "Non-Veg Curry",
      price: 320,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Kadai",
      category: "Non-Veg Curry",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Kadai",
      category: "Non-Veg Curry",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Local Chicken Gravy",
      category: "Non-Veg Curry",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Gravy",
      category: "Non-Veg Curry",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Gravy",
      category: "Non-Veg Curry",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Gravy",
      category: "Non-Veg Curry",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Egg Gravy",
      category: "Non-Veg Curry",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Sizzler",
      category: "Sizzlers",
      price: 400,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Veg. Sizzler",
      category: "Sizzlers",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Sizzler",
      category: "Sizzlers",
      price: 475,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fish Sizzler",
      category: "Sizzlers",
      price: 400,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Paneer Biryani",
      category: "Biryani & pulaw",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Biryani",
      category: "Biryani & pulaw",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Biryani",
      category: "Biryani & pulaw",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Nepali Pulaw",
      category: "Biryani & pulaw",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Pulaw",
      category: "Biryani & pulaw",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Pulaw",
      category: "Biryani & pulaw",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Hot & Sour Chicken Soup",
      category: "Soup",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Hot & Sour Mushroom Soup",
      category: "Soup",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Hot & Sour Veg. Soup",
      category: "Soup",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Soup",
      category: "Soup",
      price: 180,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mushroom Soup",
      category: "Soup",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Clear Soup",
      category: "Soup",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Tomato Soup",
      category: "Soup",
      price: 120,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Lung Fung Soup",
      category: "Soup",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chicken Mushroom Soup",
      category: "Soup",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Local Chicken Soup",
      category: "Soup",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Mutton Leg Soup",
      category: "Soup",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Double Black Label(F)",
      category: "Liquors",
      price: 10500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Double Black Label(H)",
      category: "Liquors",
      price: 5500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Double Black Label(Q)",
      category: "Liquors",
      price: 2200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Double Black Label(90ml)",
      category: "Liquors",
      price: 1150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Double Black Label(60ml)",
      category: "Liquors",
      price: 800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Double Black Label(30ml)",
      category: "Liquors",
      price: 425,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chivas Regal (F)",
      category: "Liquors",
      price: 9000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chivas Regal (H)",
      category: "Liquors",
      price: 4500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chivas Regal (Q)",
      category: "Liquors",
      price: 1800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chivas Regal (90ml)",
      category: "Liquors",
      price: 925,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chivas Regal (60ml)",
      category: "Liquors",
      price: 600,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Chivas Regal (30ml)",
      category: "Liquors",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Label (F)",
      category: "Liquors",
      price: 9000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Label (H)",
      category: "Liquors",
      price: 4500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Label (Q)",
      category: "Liquors",
      price: 1800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Label (90ml)",
      category: "Liquors",
      price: 925,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Label (60ml)",
      category: "Liquors",
      price: 600,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Label (30ml)",
      category: "Liquors",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "JD (F)",
      category: "Liquors",
      price: 8000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "JD (H)",
      category: "Liquors",
      price: 4000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "JD (Q)",
      category: "Liquors",
      price: 1625,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "JD (90ml)",
      category: "Liquors",
      price: 825,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "JD (60ml)",
      category: "Liquors",
      price: 550,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "JD (30ml)",
      category: "Liquors",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Label (F)",
      category: "Liquors",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Label (H)",
      category: "Liquors",
      price: 7000,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Label (Q)",
      category: "Liquors",
      price: 1425,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Label (90ml)",
      category: "Liquors",
      price: 725,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Label (60ml)",
      category: "Liquors",
      price: 500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Label (30ml)",
      category: "Liquors",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Absolute Vodka (F)",
      category: "Liquors",
      price: 6800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Absolute Vodka (H)",
      category: "Liquors",
      price: 3400,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Absolute Vodka (Q)",
      category: "Liquors",
      price: 1400,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Absolute Vodka (90ml)",
      category: "Liquors",
      price: 725,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Absolute Vodka (60ml)",
      category: "Liquors",
      price: 500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Absolute Vodka (30ml)",
      category: "Liquors",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vat 69 (1 ltr.) (F)",
      category: "Liquors",
      price: 6500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vat 69 (1 ltr.) (H)",
      category: "Liquors",
      price: 3250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vat 69 (1 ltr.) (Q)",
      category: "Liquors",
      price: 1325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vat 69 (1 ltr.) (90ml)",
      category: "Liquors",
      price: 675,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vat 69 (1 ltr.) (60ml)",
      category: "Liquors",
      price: 475,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Vat 69 (1 ltr.) (30ml)",
      category: "Liquors",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Chimney (F)",
      category: "Liquors",
      price: 3600,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Chimney (H)",
      category: "Liquors",
      price: 1800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Chimney (Q)",
      category: "Liquors",
      price: 900,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Chimney (90ml)",
      category: "Liquors",
      price: 475,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Chimney (60ml)",
      category: "Liquors",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Chimney (30ml)",
      category: "Liquors",
      price: 175,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Old Durbar (F)",
      category: "Liquors",
      price: 2900,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Old Durbar (H)",
      category: "Liquors",
      price: 1450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Old Durbar (Q)",
      category: "Liquors",
      price: 725,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Old Durbar (90ml)",
      category: "Liquors",
      price: 375,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Old Durbar (60ml)",
      category: "Liquors",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Old Durbar (30ml)",
      category: "Liquors",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Signature (F)",
      category: "Liquors",
      price: 2500,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Signature (H)",
      category: "Liquors",
      price: 1250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Signature (Q)",
      category: "Liquors",
      price: 625,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Signature (90ml)",
      category: "Liquors",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Signature (60ml)",
      category: "Liquors",
      price: 225,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Signature (30ml)",
      category: "Liquors",
      price: 130,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Signature (F)",
      category: "Liquors",
      price: 2300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Signature (H)",
      category: "Liquors",
      price: 1150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Signature (Q)",
      category: "Liquors",
      price: 575,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Signature (90ml)",
      category: "Liquors",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Signature (60ml)",
      category: "Liquors",
      price: 210,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Green Signature (30ml)",
      category: "Liquors",
      price: 110,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "8848 (F)",
      category: "Liquors",
      price: 2100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "8848 (H)",
      category: "Liquors",
      price: 1050,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "8848 (Q)",
      category: "Liquors",
      price: 525,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "8848 (90ml)",
      category: "Liquors",
      price: 275,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "8848 (60ml)",
      category: "Liquors",
      price: 175,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "8848 (30ml)",
      category: "Liquors",
      price: 100,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Khukuri Rum (F)",
      category: "Liquors",
      price: 1900,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Khukuri Rum (H)",
      category: "Liquors",
      price: 950,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Khukuri Rum (Q)",
      category: "Liquors",
      price: 475,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Khukuri Rum (90ml)",
      category: "Liquors",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Khukuri Rum (60ml)",
      category: "Liquors",
      price: 175,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Khukuri Rum (30ml)",
      category: "Liquors",
      price: 95,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Ruslan Vodka (F)",
      category: "Liquors",
      price: 1800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Ruslan Vodka (H)",
      category: "Liquors",
      price: 900,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Ruslan Vodka (Q)",
      category: "Liquors",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Ruslan Vodka (90ml)",
      category: "Liquors",
      price: 240,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Ruslan Vodka (60ml)",
      category: "Liquors",
      price: 165,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Ruslan Vodka (30ml)",
      category: "Liquors",
      price: 85,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Grand Master XXX (F)",
      category: "Liquors",
      price: 1800,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Grand Master XXX (H)",
      category: "Liquors",
      price: 900,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Grand Master XXX (Q)",
      category: "Liquors",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Grand Master XXX (90ml)",
      category: "Liquors",
      price: 240,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Grand Master XXX (60ml)",
      category: "Liquors",
      price: 165,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Grand Master XXX (30ml)",
      category: "Liquors",
      price: 85,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Oak (F)",
      category: "Liquors",
      price: 1400,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Oak (H)",
      category: "Liquors",
      price: 700,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Oak (Q)",
      category: "Liquors",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Black Oak (90ml)",
      category: "Liquors",
      price: 175,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Highlander (F)",
      category: "Liquors",
      price: 1300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Highlander (H)",
      category: "Liquors",
      price: 650,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Highlander (Q)",
      category: "Liquors",
      price: 325,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Highlander (90ml)",
      category: "Liquors",
      price: 170,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Golden Oak (F)",
      category: "Liquors",
      price: 1200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Golden Oak (H)",
      category: "Liquors",
      price: 600,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Golden Oak (Q)",
      category: "Liquors",
      price: 300,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Golden Oak (90ml)",
      category: "Liquors",
      price: 160,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Gorkha Strong",
      category: "Beer",
      price: 350,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Budwiser",
      category: "Beer",
      price: 400,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Tuborg Strong",
      category: "Beer",
      price: 450,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Carlsberg",
      category: "Beer",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Tuborg Small",
      category: "Beer",
      price: 225,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Arna 8,Gorkha 8,Mustang 8",
      category: "Beer",
      price: 175,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Budwiser Small",
      category: "Beer",
      price: 160,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Golden Oak (90ml)",
      category: "Liquors",
      price: 160,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Lemon Sprite",
      category: "Refreshment Drinks",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Masala Coke",
      category: "Refreshment Drinks",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Nimbu Pani",
      category: "Refreshment Drinks",
      price: 50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Lemon Soda",
      category: "Refreshment Drinks",
      price: 80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fresh Lem water sweet",
      category: "Refreshment Drinks",
      price: 60,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Fresh Lem water salt",
      category: "Refreshment Drinks",
      price: 60,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Jal Jeera Pani",
      category: "Refreshment Drinks",
      price: 50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Apple Cider",
      category: "Soft Drinks",
      price: 200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Bull Blue",
      category: "Soft Drinks",
      price: 250,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Cocktail Juice Can",
      category: "Soft Drinks",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Red Bull (Max Tiger",
      category: "Soft Drinks",
      price: 150,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Badam Juice",
      category: "Soft Drinks",
      price: 110,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Coke,Fanta,Sprite(g)",
      category: "Soft Drinks",
      price: 50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Hinwa",
      category: "Wine",
      price: 900,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Devine",
      category: "Wine",
      price: 850,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Canvas",
      category: "Wine",
      price: 950,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Canary",
      category: "Wine",
      price: 850,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
    Product(
      name: "Aroma",
      category: "Wine",
      price: 1200,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
    ),
  ];

  static get data => products;

  // List <Object?>get length =>  products=[];
}
